<web:page>
  <web:sql>deldateinv</web:sql>
  <web:sql_type>delete</web:sql_type>
  <web:db>Login</web:db>
  <web:successMsg>数据保存成功！</web:successMsg>
  <web:failMsg>数据保存失败！</web:failMsg>
  <web:url>inventory.aspx</web:url>
  <web:target>parent</web:target>
  <web:template>template/synear/common/invendel.vm</web:template>
</web:page>