<web:page>
  <web:sql>insertFzPreOrder</web:sql>
  <web:db>Login</web:db>
  <web:multiValue>cinvbasdocid,cinventoryid,cpackunitid,cunitid,nnumber,crowno,npacknumber,nprice,cunitid,nmny,pk_preorder_b,cpriceitemtableid,cpriceid,cporjectid,disnum,disnum2</web:multiValue>
  <web:successMsg>数据保存成功！</web:successMsg>
  <web:failMsg>数据保存失败！</web:failMsg>
  <web:url>preorder.aspx</web:url>
  <web:target>parent</web:target>
  <web:template>template/synear/common/test.vm</web:template>
</web:page>