<web:page>
  <web:sql>getFzCustomerInfo##getFzCustomerInfo##getFzCustomerInfo</web:sql>
  <web:db>Login</web:db>
  <web:successMsg>数据保存成功！</web:successMsg>
  <web:failMsg>数据保存失败！</web:failMsg>
  <web:url>preorder.aspx</web:url>
  <web:target>parent</web:target>
  <web:template>template/synear/common/test.vm</web:template>
</web:page>