<web:page>
  <web:sql>updatebatchorderdriver2</web:sql>
  <web:sql_type>update</web:sql_type>
  <web:db>Login</web:db>
  <web:multiValue>vreceiptcodes</web:multiValue>
  <web:successMsg>数据保存成功！</web:successMsg>
  <web:failMsg>数据保存失败！</web:failMsg>
  <web:url>VehiclePrint.aspx</web:url>
  <web:target>parent</web:target>
  <web:template>template/synear/common/message11.vm</web:template>
</web:page>