<web:page>
<web:sql>selnccorpothername</web:sql>
<web:sql_type>select</web:sql_type>
<web:multiValue>crowno,carriveorder_bid,corderid,corder_bid,cbaseid,cmangid,narrvnum,noriginalcurmny,noriginalcurprice,cwarehouseid,dproducedate,dvaliddate,ivalidday,nprice,nmoney,vdef4</web:multiValue>
  <web:failMsg>数据保存到NC时失败!</web:failMsg>
  <web:url>PrayBillList.aspx</web:url>
  <web:target>parent</web:target>
  <web:template>template\synear\Operation\23.vm</web:template>
</web:page>