<web:page>
  <web:sql>fixedcontractsaveadd</web:sql>
  <web:sql_type>insert</web:sql_type>
  <web:db>Login</web:db>
  <web:multiValue>qbh,lsh,invname,invspec,vnote,htbh,sl,dj,je,deptid,fktk,deptname</web:multiValue>
  <web:successMsg>数据保存成功！</web:successMsg>
  <web:failMsg>数据保存失败！</web:failMsg>
  <web:url>fixedcontract.aspx</web:url>
  <web:target>parent</web:target>
  <web:template>template/synear/common/message.vm</web:template>
</web:page>