<web:page>
  <web:sql>insertpo</web:sql>
  <web:sql_type>insert</web:sql_type>
  <web:db>Login</web:db>
  <web:multiValue>cmangid,corderid,cbaseid,corder_bid,cwarehouseid,narrvnum,nmoney,noriginalcurmny,carriveorder_bid,crowno,vdef4,norgtaxprice,csourcebilltype,csourcebillid,csourcerowid,cpraybillid,cpraybill_bid,nmoney,noriginalcurmny,nprice,huixie,noriginalcurprice</web:multiValue>
  <web:successMsg>数据保存成功！</web:successMsg>
  <web:failMsg>数据保存失败！</web:failMsg>
  <web:url>PrayBillList.aspx</web:url>
  <web:target>parent</web:target>
  <web:template>template/synear/common/message.vm</web:template>
</web:page>