<web:page>
  <web:sql>delcompare</web:sql>
  <web:sql_type>delete</web:sql_type>
  <web:db>Login</web:db>
  <web:successMsg>É¾³ý³É¹¦£¡</web:successMsg>
  <web:failMsg>É¾³ýÊ§°Ü£¡</web:failMsg>
  <web:url>comparelist.aspx</web:url>
  <web:target>parent</web:target>
  <web:template>template/synear/common/message.vm</web:template>
</web:page>