<web:page>
  <web:sql>insertDaystock</web:sql>
  <web:sql_type>insert</web:sql_type>
  <web:multiValue>invcode,fsum,insum,outnum,enum,diffs,read,cls</web:multiValue>
  <web:successMsg>数据保存成功！</web:successMsg>
  <web:failMsg>数据保存失败！</web:failMsg>
  <web:url>selectyjjb.aspx</web:url>
  <web:target>parent</web:target>
  <web:template>template/synear/common/message.vm</web:template>
</web:page>