<web:page>
  <web:sql>snbomsavedit</web:sql>
  <web:sql_type>update</web:sql_type>
  <web:db>Login</web:db>
  <web:multiValue>ischild,fhwlbomid,F_nc_pk,masname,invtype,F_number,ERRU,ERRD,DIS,DISNUM,PROCID,CLSID,FLAG</web:multiValue>
  <web:successMsg>数据保存成功！</web:successMsg>
  <web:failMsg>数据保存失败！</web:failMsg>
  <web:url>invnamebaobomdetail.aspx</web:url>
  <web:target>parent</web:target>
  <web:template>template/synear/common/messagebom.vm</web:template>
</web:page>