<web:page>
  <web:sql>updateregistertender</web:sql>
  <web:sql_type>update</web:sql_type>
  <web:db>Login</web:db>
  <web:multiValue>mantype1,mantypehid</web:multiValue>
  <web:successMsg>数据修改成功！</web:successMsg>
  <web:failMsg>数据修改失败！</web:failMsg>
  <web:url>registertend.aspx</web:url>
  <web:target>parent</web:target>
  <web:template>template/synear/common/message.vm</web:template>
</web:page>