<web:page>
  <web:sql>uptend</web:sql>
  <web:sql_type>update</web:sql_type>
  <web:db>Login</web:db>
   <web:multiValue>pid,tenduserid,tendprice,tendtime,tendbak,tendoter,quantity</web:multiValue>
  <web:successMsg>数据保存成功！</web:successMsg>
  <web:failMsg>数据保存失败！</web:failMsg>
  <web:url>tenderinfo.aspx</web:url>
  <web:target>parent</web:target>
  <web:template>template/synear/common/message.vm</web:template>
</web:page>