<web:page>
  <web:sql>delFzPartSalePlan</web:sql>
  <web:sql_type>insert</web:sql_type>
  <web:db>Login</web:db>
  <web:successMsg>数据退回成功！</web:successMsg>
  <web:failMsg>数据退回失败！</web:failMsg>
  <web:url>partsalePlan.aspx</web:url>
  <web:target>parent</web:target>
  <web:template>template/synear/common/message.vm</web:template>
</web:page>