<web:page>
  <web:sql>createYearReport</web:sql>
  <web:sql_type>insert</web:sql_type>
  <web:db>Login</web:db>
  <web:multiValue>categorys,accsubjIds,xiangmus</web:multiValue>
  <web:successMsg>年度报表创建成功！</web:successMsg>
  <web:failMsg>年度报表创建失败！</web:failMsg>
  <web:url>queryYearReport.aspx</web:url>
  <web:template>template/synear/common/messagezzfy.vm</web:template>
</web:page>