<web:page>
  <web:sql>updateInvbasCategory</web:sql>
  <web:sql_type>update</web:sql_type>
  <web:db>Login</web:db>
  <web:multiValue>checkids</web:multiValue>
  <web:successMsg>数据保存成功！</web:successMsg>
  <web:failMsg>数据保存失败！</web:failMsg>
  <web:url>setChanLiangItem.aspx</web:url>
  <web:template>template/synear/common/messagezzfy.vm</web:template>
</web:page>