<web:page>
  <web:sql>updateYearReport</web:sql>
  <web:sql_type>update</web:sql_type>
  <web:db>Login</web:db>
  <web:multiValue>itemss,monthbudgets,monthbudgettonss</web:multiValue>
  <web:successMsg>数据1保存成功！</web:successMsg>
  <web:failMsg>数据1保存失败！</web:failMsg>
  <web:template>template/synear/common/messagezzfy.vm</web:template>
</web:page>