<web:page>
  <web:sql>deleteByDeptId</web:sql>
  <web:sql_type>delete</web:sql_type>
  <web:db>Login</web:db>
  <web:successMsg>删除成功！</web:successMsg>
  <web:failMsg>删除失败！</web:failMsg>
  <web:url>dept.aspx</web:url>
  <web:target>parent</web:target>
 <web:template>videosession/message.vm</web:template>
</web:page>
