<web:page>
  <web:sql>updateVsessionVStateOver</web:sql>
  <web:sql_type>update</web:sql_type>
  <web:multiValue>pk_aids</web:multiValue>
  <web:successMsg>操作成功！</web:successMsg>
  <web:failMsg>操作失败！</web:failMsg>
  <web:url>vsessionapply.aspx</web:url>
  <web:template>videosession/message.vm</web:template>
</web:page>