<web:page>
  <web:sql>updatemesgend</web:sql>
  <web:sql_type>update</web:sql_type>
  <web:db>Login</web:db>
  <web:successMsg>数据保存成功！</web:successMsg>
  <web:failMsg>数据保存失败！</web:failMsg>
  <web:url>receiveprob.aspx</web:url>
  <web:target>parent</web:target>
  <web:template>ITReport/message1.vm</web:template>
</web:page>