<web:page>
  <web:sql>updatebudget2</web:sql>
  <web:sql_type>update</web:sql_type>
  <web:db>Login</web:db>
  <web:successMsg>上报成功！</web:successMsg>
  <web:failMsg>上报失败！</web:failMsg>
  <web:url>budgetlist.aspx</web:url>
  <web:target>parent</web:target>
  <web:template>template/synear/common/message.vm</web:template>
</web:page>