<web:page>
  <web:sql>delbudget</web:sql>
  <web:sql_type>insert</web:sql_type>
  <web:db>Login</web:db>
  <web:successMsg>É¾³ı³É¹¦£¡</web:successMsg>
  <web:failMsg>É¾³ıÊ§°Ü£¡</web:failMsg>
  <web:url>budgetlist.aspx</web:url>
  <web:target>parent</web:target>
  <web:template>template/synear/common/message.vm</web:template>
</web:page>