<web:page>
  <web:sql>inrole</web:sql>
  <web:sql_type>update</web:sql_type>
  <web:multiValue>roleid</web:multiValue>
  <web:db>Login</web:db>
  <web:url>roleuser.aspx</web:url>
  <web:target>parent</web:target>
  <web:template>template/synear/common/save1.vm</web:template>
</web:page>