<web:page>
  <web:sql>inserinv</web:sql>
  <web:sql_type>insert</web:sql_type>
  <web:multiValue>itemcode,itemdesc,itemspec,unit,snum,nnum,dif,bad,sty,nty,twe,oth,top,pk_invcl</web:multiValue>
  <web:db>Login</web:db>
  <web:successMsg>数据保存成功！</web:successMsg>
  <web:failMsg>数据保存失败！</web:failMsg>
  <web:url>inventory.aspx</web:url>
  <web:target>parent</web:target>
  <web:template>template/synear/common/invensave.vm</web:template>
</web:page>