<web:page>
  <web:sql>dispatchsavedit</web:sql>
  <web:sql_type>insert</web:sql_type>
  <web:db>Login</web:db>
  <web:multiValue>pk_invmandoc,pk_invbasdoc,nnumber,fnnumber,taxrate,money,hmoney,omoney,ohmoney,ct,bt_id,pk_measdoc,fpk_measdoc,pk_taxitems,mainmeasrate,taxmoney,otaxmoney</web:multiValue>
  <web:successMsg>数据保存成功！</web:successMsg>
  <web:failMsg>数据保存失败！</web:failMsg>
  <web:url>dispatchedit.aspx</web:url>
  <web:target>parent</web:target>
  <web:template>template/synear/common/messagedps.vm</web:template>
</web:page>